# Generated by Django 5.0.3 on 2024-03-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
